#ifndef __ATTR_CONFIG_H__
#define __ATTR_CONFIG_H__

#ifndef CFG_HAVE_ATTRIBUTES
# define CFG_HAVE_ATTRIBUTES		1
#endif /* !CFG_HAVE_ATTRIBUTES */

#ifndef CFG_ATTRIBUTE_UNUSED
# define CFG_ATTRIBUTE_UNUSED		1
#endif /* !CFG_ATTRIBUTE_UNUSED */

#ifndef CFG_ATTRIBUTE_FORMAT
# define CFG_ATTRIBUTE_FORMAT		1
#endif /* !CFG_ATTRIBUTE_FORMAT */

#ifndef CFG_ATTRIBUTE_NONNULL
# define CFG_ATTRIBUTE_NONNULL		1
#endif /* !CFG_ATTRIBUTE_NONNULL */

#endif /* __ATTR_CONFIG_H__ */
